### ISSUE TITLE
typo in configuration key

### ISSUE THREAD

**Issue by jbermudezcabrera** [Joel-hanson/django-aws-eb-deploy#21]
**Describe the bug**
The usage example shown [here](https://github.com/Joel-hanson/django-aws-eb-deploy#example) states that the entry for running flake in the workflow is `flake8: true`. However the actual implementation expects a config key called `flask8` as stated below in the [docs](https://github.com/Joel-hanson/django-aws-eb-deploy#required-setup)

**To Reproduce**
1. Use the action with `flake8: true or false`
2. Run it
3. See warning in the `Django aws eb deployment` step

> [warning]Unexpected input(s) 'flake8', valid inputs are ['entryPoint', 'args', 'flask8', 'flake8_config_file', 'python_version', 'aws_access_key_id', 'aws_secret_access_key', 'django_path', 'unit_testing', 'min_coverage', 'deploy', 'postgresql_required', 'security_check']

**Expected behavior**
I think that the correct name of the config key should be `flake8` instead `flask8`

**Comment by Joel-hanson** [comment]
Thanks a lot, @jbermudezcabrera for pointing this out. Have fixed it in the PR #22

**Comment by jbermudezcabrera** [comment]
Thank you for the quick fix 👍
